Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1176, in exec_module
  File "<frozen site>", line 635, in <module>
  File "<frozen site>", line 618, in main
  File "<frozen site>", line 550, in venv
  File "<frozen site>", line 405, in addsitepackages
  File "<frozen site>", line 247, in addsitedir
  File "<frozen site>", line 206, in addpackage
  File "<string>", line 1, in <module>
  File "/home/alexander/lib/python3.12/site-packages/__editable___vasp_analyzer_0_2_finder.py", line 7, in <module>
    from pathlib import Path
  File "/home/alexander/anaconda3/lib/python3.12/pathlib.py", line 8, in <module>
    import fnmatch
  File "/home/alexander/anaconda3/lib/python3.12/fnmatch.py", line 14, in <module>
    import re
  File "/home/alexander/anaconda3/lib/python3.12/re/__init__.py", line 124, in <module>
    import enum
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 819, in module_from_spec
  File "<frozen importlib._bootstrap>", line 798, in _init_module_attrs
  File "<frozen importlib._bootstrap>", line 638, in cached
  File "<frozen importlib._bootstrap_external>", line 614, in _get_cached
  File "<frozen importlib._bootstrap_external>", line 508, in cache_from_source
  File "<frozen importlib._bootstrap_external>", line 132, in _path_split
KeyboardInterrupt
