Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1176, in exec_module
  File "<frozen site>", line 635, in <module>
  File "<frozen site>", line 618, in main
  File "<frozen site>", line 550, in venv
  File "<frozen site>", line 405, in addsitepackages
  File "<frozen site>", line 247, in addsitedir
  File "<frozen site>", line 206, in addpackage
  File "<string>", line 1, in <module>
  File "/home/alexander/lib/python3.12/site-packages/__editable___vasp_analyzer_0_2_finder.py", line 7, in <module>
    from pathlib import Path
  File "/home/alexander/anaconda3/lib/python3.12/pathlib.py", line 20, in <module>
    from urllib.parse import quote_from_bytes as urlquote_from_bytes
  File "/home/alexander/anaconda3/lib/python3.12/urllib/parse.py", line 40, in <module>
    import ipaddress
  File "/home/alexander/anaconda3/lib/python3.12/ipaddress.py", line 2317, in <module>
    class _IPv6Constants:
  File "/home/alexander/anaconda3/lib/python3.12/ipaddress.py", line 2321, in _IPv6Constants
    _multicast_network = IPv6Network('ff00::/8')
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/anaconda3/lib/python3.12/ipaddress.py", line 2274, in __init__
    self.network_address = IPv6Address(addr)
                           ^^^^^^^^^^^^^^^^^
  File "/home/alexander/anaconda3/lib/python3.12/ipaddress.py", line 1956, in __init__
    addr_str, self._scope_id = self._split_scope_id(addr_str)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/anaconda3/lib/python3.12/ipaddress.py", line 1885, in _split_scope_id
    @staticmethod

KeyboardInterrupt
